### ISSUE TITLE
Visual Issue

### ISSUE THREAD

**Issue by Noob1e** [ElvUI-WotLK/ElvUI_SwingBar#3]
The swings bars are not as smooth as cast bars. Let's say, casts bars are like 60 fps and swing bars like 15 fps. Looks like they're lagging.

It's really annoying. Makes me check my FPS all the time.

**Comment by Hansrutger** [comment]
Would be 10/10 bars if you added a "smoothness" option indeed! Looks clunky, don't get me wrong it's better than creating a custom weakaura and having to go through with all the annoying timers, but just something to make it look slightly smoother would be perfect!

**Comment by Crumdidlyumshis** [comment]
This issue appears randomly, and I believe it is due to specific software settings. Hard to pinpoint. However, if you are on the latest Windows 10 build of version 2004, you can toggle the following graphics setting. After I toggled this setting in Windows 10, my ElvUI_SwingBar appeared to be really smooth. This may differ for other users, but this is what worked for me.

![image](https://user-images.githubusercontent.com/7307335/87389652-bad6ca80-c56c-11ea-88fe-0ebb03b44169.png)

**Comment by Crumdidlyumshis** [comment]
Note: it shows retail by default; regardless of version.

**Comment by Noob1e** [comment]
It's still same. Also, everything else works fine. Castbars, WeakAuras bars etc.

**Comment by Crumdidlyumshis** [comment]
Take a look at this issue in pfUI as it is very similar to this. https://github.com/shagu/pfUI/issues/115

Like I said, its super random. I had this same issue the other day when I pushed the new changes... AND before I pushed the new changes. After I toggled the windows 10 setting, it seemed to just work perfectly.  I know this can vary for all users with different hardware/software.

**Comment by Noob1e** [comment]
I updated my windows and now it's working perfectly. Thanks Crumdidlyumshis :)

**Comment by Noob1e** [comment]
btw, is there any way to show only main hand swings or change the colors of dual-wield?
